"use client";
import { useMemo,useState } from "react";
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, CheckCircle2, Clock3, Download, Filter, Search } from "lucide-react";
import { Badge, GlassCard, Section, SectionHeader, useToast } from "@/components/ui";

const tx=[
["TX-8841","09:14","IN","Alpha",84000,"SUCCESS","ปิดดีล Sector A"],["TX-8840","09:12","IN","Delta",210000,"SUCCESS","รับเงินจาก Client B"],["TX-8839","09:08","OUT","Beta",42000,"SUCCESS","ค่าดำเนินการ"],["TX-8838","09:05","IN","Delta",96000,"SUCCESS","Commission Q2"],["TX-8837","08:58","OUT","Alpha",18000,"PENDING","รอตรวจสอบบัญชี"],["TX-8836","08:52","OUT","Zeta",55000,"FAILED","ข้อมูลธนาคารไม่ถูกต้อง"],["TX-8835","08:44","IN","Beta",130000,"SUCCESS","Settlement D"]
] as const;
export default function SectionTransactions(){const [tab,setTab]=useState("ALL"),[q,setQ]=useState("");const {show,ToastEl}=useToast();const rows=useMemo(()=>tx.filter(t=>(tab==="ALL"||t[2]===tab)&&t.join(" ").toLowerCase().includes(q.toLowerCase())),[tab,q]);const exportData=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(tx,null,2)],{type:"application/json"}));a.download="transactions.json";a.click();show("ส่งออกข้อมูลแล้ว","success")};
return <Section>{ToastEl}<SectionHeader title="ธุรกรรม" sub="LIVE TRANSACTION LEDGER"><button className="glow-btn flex items-center gap-2" onClick={exportData}><Download size={13}/>Export</button></SectionHeader>
<div className="grid grid-cols-3 gap-3">{[{l:"เงินเข้า",v:"฿520K",I:ArrowDownLeft,c:"#37D67A"},{l:"เงินออก",v:"฿115K",I:ArrowUpRight,c:"#FF5C5C"},{l:"รอตรวจ",v:"1",I:Clock3,c:"#FFB648"}].map(({l,v,I,c})=><div key={l} className="lux-card p-3"><I size={15} color={c}/><p className="mt-2 font-mono text-lg font-bold" style={{color:c}}>{v}</p><p className="text-xs text-muted-foreground">{l}</p></div>)}</div>
<div className="flex gap-2"><label className="relative flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input className="lux-input pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา ID, Agent, หมายเหตุ"/></label><button className="glow-btn" onClick={()=>show("ใช้ตัวกรองตามช่วงเวลาได้เร็ว ๆ นี้","warning")}><Filter size={13}/></button></div>
<div className="flex gap-2">{["ALL","IN","OUT"].map(x=><button key={x} onClick={()=>setTab(x)} className="rounded-xl border px-4 py-2 font-mono text-[10px]" style={{borderColor:tab===x?"#D8B46B":"rgba(255,255,255,.1)",color:tab===x?"#D8B46B":"rgba(255,255,255,.4)",background:tab===x?"rgba(216,180,107,.08)":"transparent"}}>{x}</button>)}</div>
<GlassCard style={{padding:0}}>{rows.map((t,i)=>{const incoming=t[2]==="IN",status=t[5];const S=status==="SUCCESS"?CheckCircle2:status==="PENDING"?Clock3:AlertTriangle;const color=status==="SUCCESS"?"#37D67A":status==="PENDING"?"#FFB648":"#FF5C5C";return <button key={t[0]} onClick={()=>show(`${t[0]} • ฿${Number(t[4]).toLocaleString()}`,status==="FAILED"?"danger":status==="PENDING"?"warning":"success")} className="flex w-full items-center gap-3 border-b border-white/5 p-4 text-left last:border-0"><span className="icon-circle" style={{background:incoming?"rgba(55,214,122,.1)":"rgba(255,92,92,.1)"}}>{incoming?<ArrowDownLeft size={15} color="#37D67A"/>:<ArrowUpRight size={15} color="#FF5C5C"/>}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="font-mono text-xs">{t[0]}</b><S size={12} color={color}/></div><p className="truncate text-sm text-muted-foreground">{t[6]}</p><p className="font-mono text-[9px] text-muted-foreground">{t[3]} • {t[1]}</p></div><b className="font-mono text-sm" style={{color:incoming?"#37D67A":"#FF5C5C"}}>{incoming?"+":"-"}฿{Number(t[4]).toLocaleString()}</b></button>})}</GlassCard>
<GlassCard style={{padding:18}}><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Settlement integrity</p><p className="text-xs text-muted-foreground">ตรวจสอบสำเร็จ 98.7% ใน 24 ชั่วโมง</p></div><Badge text="SECURE" color="success" dot/></div><div className="prog-bar mt-4"><div className="prog-fill bg-emerald-400" style={{width:"98.7%"}}/></div></GlassCard></Section>}
